spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #false:不作为一个客户端注册到注册中心
    fetchRegistry: false  #为true时可以启动，但报异常：Cannot execute