package com.sfc.sso_server.dao.interfaces;

import com.sfc.sso_server.entity.t_teacher_gw;

public interface t_teacher_gwMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_gw
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_gw
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    int insert(t_teacher_gw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_gw
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    int insertSelective(t_teacher_gw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_gw
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    t_teacher_gw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_gw
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    int updateByPrimaryKeySelective(t_teacher_gw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_gw
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    int updateByPrimaryKey(t_teacher_gw record);
}