package com.sfc.sso_server.dao.interfaces;

import com.sfc.sso_server.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 24 22:27:36 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 24 22:27:36 CST 2019
     */
    int insertSelective(User record);

    List<User> selectUserList();
}