package com.sfc.sso_server.entity;

public class t_group_gw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_gw.id
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_gw.name
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_gw.number
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_gw.teacherid
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private Integer teacherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_gw.id
     *
     * @return the value of t_group_gw.id
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_gw.id
     *
     * @param id the value for t_group_gw.id
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_gw.name
     *
     * @return the value of t_group_gw.name
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_gw.name
     *
     * @param name the value for t_group_gw.name
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_gw.number
     *
     * @return the value of t_group_gw.number
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_gw.number
     *
     * @param number the value for t_group_gw.number
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_gw.teacherid
     *
     * @return the value of t_group_gw.teacherid
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_gw.teacherid
     *
     * @param teacherid the value for t_group_gw.teacherid
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }
}