package com.sfc.sso_server.entity;

public class t_teacher_gw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_gw.id
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_gw.name
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher_gw.age
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_gw.id
     *
     * @return the value of t_teacher_gw.id
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_gw.id
     *
     * @param id the value for t_teacher_gw.id
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_gw.name
     *
     * @return the value of t_teacher_gw.name
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_gw.name
     *
     * @param name the value for t_teacher_gw.name
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher_gw.age
     *
     * @return the value of t_teacher_gw.age
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher_gw.age
     *
     * @param age the value for t_teacher_gw.age
     *
     * @mbg.generated Sun Oct 20 11:32:48 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}