info:
  description: SSO
  
server:
  port: 8080

spring:
  datasource:
    name:  king
    url: jdbc:mysql://localhost:3306/openapi?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
  druid:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 30000  #每30秒运行一次空闲连接回收器
    minEvictableIdleTimeMillis: 1800000  #池中的连接空闲30分钟后被回收,默认值就是30分钟
    validationQuery: select 1 #验证连接是否可用，使用的SQL语句
    testWhileIdle: true #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
    testOnBorrow: false #借出连接时不要测试，否则很影响性能
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache:  false
    mode:  HTML5
    endoding:  UTF-8
  #redis配置
  redis:
    #Redis端口
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接超时时间（毫秒）
    timeout: 3000
    ## 连接池中的最大连接数
    poolMaxTotal: 10
    ## 连接池中的最大空闲连接
    poolMaxIdle: 10
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
    poolMaxWait: 3
# mybatis配置
mybatis:
  mapper-locations: classpath:com/sfc/sso_server/dao/impl/*.xml  #这里是mapper的绝对路径
  type-aliases-package: com.sfc.sso_server.entity  #这里是实体类的绝对路径

# 打印sql接口绝对路径
logging:
  level:
    com.sfc.sso_server.dao.interfaces: DEBUG

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql